apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-and-back
  labels:
    app: front-back
spec:
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
      - name: front-end
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: back-end
        image: debian
        command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: svc-front-back
  labels:
    app: front-back
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: front-back


